language: c

os: linux
dist: trusty


compiler: arm-none-eabi-gcc


before_install:
  -  sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  -  sudo apt-get update -q
  -  sudo apt-get install gcc-arm-embedded -y


script: make ARCH=arm PLAT=STM32F429I_DISCO CPU=cortex-m4 ARMV=armv7e-m V=2

